path_number: 1
#           01    02    03    04    05    06    07    08    09    10    11    12    13
V_1:   [     1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1]
O_0:   [     0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0]
O_1:   [     0,    0,    0,    0,    0,    0,  0.1,  0.1,  0.1, -0.1, -0.1, -0.1, -0.1]
O_2:   [     0,    0,    0,    0,    0,  0.3,  0.3,  0.3,  0.3, -0.3, -0.3, -0.3, -0.3]
O_3:   [   0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2]
O_4:   [   0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.0, -0.2, -0.2, -0.2, -0.2, -0.2, -0.2]


#O_2:   [   0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2]
