    	<param name="costmap_res" type="double" value="0.1" />
    	<param name="LETHAL_radius" type="double" value="0.1" />
    	<param name="INFLATION_radius" type="double" value="0.3" />
    	
        <param name="pso_inertia" type="double" value="0.1" />
    	<param name="pso_c1" type="double" value="0.30" />
        <param name="pso_c2" type="double" value="0.10" />
    	<param name="pso_speed_gain" value="20.0" />
    	<param name="pso_goal_gain"  value="20.00" />
    	<param name="pso_cost_gain"  value="1.00" />
        <param name="pso_particle_no"  value="30" />
        <param name="pso_iteration"  value="10" />
        <param name="path_piece_no"  value="5" />
        <param name="omega_x"  value="0.4" />
        
        <param name="Travel_cost_inc"  value="0.0" />
        <param name="Lethal_cost_inc"  value="10.0" />
        <param name="Inflation_cost_inc"  value="3.0" />
        <param name="b"  value="0.4" />
        <param name="Watching_horizon"  value="3.2" />
        <param name="sample"  value="20" />
        <param name="demo_mode"  value="false" />
costmap_res: 0.1
LETHAL_radius: 0.1
INFLATION_radius: 0.3
pso_inertia
pso_c1
pso_c2
pso_speed_gain
pso_goal_gain
pso_cost_gain
pso_particle_no
pso_iteration
path_piece_no
omega_x
Travel_cost_inc
Lethal_cost_inc
Inflation_cost_inc
b
Watching_horizon


